# 项目相关配置
systemplus:
  # 名称
  name: 系统管理后台
  # 版本
  version: 3.2.0
  # 版权年份
  copyrightYear: 2020
  # 文件上传路径
  #profile: D:/lawyerdata/files/ #开发环境
  profile: D:/data/systemplus/files/ #测试环境
  #profile: /lawyerdata/files/ #正式环境
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务端口
  #port: 18080
  #servlet:
    # 项目contextPath
    #context-path: /lawyer
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    com.mkst.mini.systemplus: debug
    org.springframework: WARN
    org.spring.springboot.dao: ERROR

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
  onlineAsyTime: 10000 #更新session信息时的缓冲时间,单位毫秒
  
# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.mkst.mini.systemplus
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    #configLocation: classpath:mapper/mybatis-config.xml
    configuration:
       cache-enabled: true #全局映射器启用缓存
       map-underscore-to-camel-case: true #驼峰式命名
       use-generated-keys: true #允许 JDBC 支持自动生成主键
       default-executor-type: reuse #配置默认的执行器
       log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #指定 MyBatis 所用日志的具体实现
       #default-statement-timeout: 600 #默认超时时间

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  #spring-redis的配置
  redis:
    run: false #是否开启 位于RedisUtils
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /portal
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

   
# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen: 
  # 作者
  author: liuzhiping
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.mkst.mini.systemplus.appmanager
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix: sys_
alipay:
  dev: true #默认false,为true表示使用沙箱环境
  sign-type: RSA2 #签名算法
  app-id: #应用ID
  private-key: #应用私钥
  alipay-public-key: #支付宝公钥
  
wx:
  mp:
    configs:
      - appid: wx6fd0c6d1c5b0b304
        secret: 5ebbcce2219c576b51a0a618a93d5946
        token: 53fac2fc12ab4ed4aa3f9444279d0db6
        aesKey: LYdzuGsWIdg45tUhlRq8wqD99BMmnjjYdhv6co41yhb

sm4:
  key: 76C63180C2606ED1F47B852De5012156